name: Rustfmt

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
          source $HOME/.cargo/env
          rustup component add clippy rustfmt
        shell: bash
      - name: Run rustfmt
        run: |
          source $HOME/.cargo/env
          make format
        shell: bash